name: Label Management

on:
  pull_request:
    types:
      - labeled

jobs:
  debug_labels:
    runs-on: ubuntu-latest
    name: Debug Label Event
    steps:
      - name: Print Label Event Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event }}"
