name: Slackbot on release

on:
  release:
    types:
      - published

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Releases
        uses: jeffersfp/slack-release-notifier@v1.0.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
